---
title: "Rust/AnyhowのTips"
emoji: "🦀"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ["Rust"]
published: true
---

Rust初学者が苦戦するのことの一つにエラー処理があると思います。自分もそうでした。例外のあるプログラミング言語(C++, C#, Java)から来ると、RustのResult、Optionはとっつきにくさ感じますが、使いこなせば超強力な武器になります。

[anyhow](https://github.com/dtolnay/anyhow)は2019頃に出てきたライブラリで、筆者の観測範囲[^1]では2021年10月時点におけるデファクトのエラー管理crateと言って良いと思う。ちなみにanyhowのコア開発者のDavid Tolnay氏はRust界では著名な開発者で、[serde-rs](https://github.com/serde-rs)がよく知られています。本記事では、anyhowを使いこなすためのTipsを紹介してみます。

## なぜanyhowを使うのか

なぜanyhowを使うべきなのかは他の記事[^2][^3]によくまとまっているのでここでは詳細に書きませんが、以下のような理由があります。
* 他のエラー型から`anyhow::Error`への変換が容易
* エラーの階層化
* Backtrace
* `anyhow!`, `ensure!`, `bail!`, `ensure!`等の便利マクロ

## `anyhow::Result`

このようなtypeエイリアスが定義されているので、
```rust
pub type Result<T, E = Error> = core::result::Result<T, E>;
```

Resultに二つ型を指定するより
```rust
fn foo() -> Result<(), anyhow::Error> {
    ...
}
```

このように`anyhow::Result`を使ったほうがスッキリ書けますね。
```rust
use anyhow::Result;

fn foo() -> Result<()> {
    ...
}
```

## main関数の戻りの型に`anyhow::Result`を使う

main関数の戻り値は[std::process::Termination](https://doc.rust-lang.org/std/process/trait.Termination.html)を実装している必要がありますが、以下のようなブランケット実装があるので`anyhow::Result`を返すことができます。

```rust
impl<E: Debug> Termination for Result<(), E>
```

つまり

```rust
fn main() -> anyhow::Result<()> {
    Ok(())
}
```

asyncもOK
```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    Ok(())
}
```

## テスト関数の戻りの型に`anyhow::Result`を使う

以下のように全てのResult型でunwrapするとコードが長くなってしまいます。
```rust
#[test]
fn test_foo() {
    Foo::new().unwrap().bar().unwrap();
}
```

この場合戻り値の型を`anyhow::Result`にして`?`を使うとスッキリかけます。
```rust
#[test]
fn test_foo() -> anyhow::Result<()> {
    Foo::new()?.bar()?;
    Ok(())
}
```

## Backtrace

Backtraceを表示させるには、nightlyツールチェインを使うかstableで以下のようにfeatureを指定する必要があります。

```toml
anyhow = { version = "1", features = ["backtrace"] }
```

またプログラムを実行するときは環境変数`RUST_BACKTRACE=1`をつける必要があります。

## `{}`, `{:?}`, `{:#}`, `{:#?}`の違い

`anyhow::Error`を`{}`と`{:?}`で文字列出力したときの結果が異なります。

* `{}`の場合

エラーの文字列のみが出力されます。このようなプログラムを実行すると`foo error`が出力されます。

```rust
use anyhow::{Context, Result};

fn foo() -> Result<()> {
    bar().context("foo error")?;
    Ok(())
}

fn bar() -> Result<()> {
    baz().context("bar error")?;
    Ok(())
}

fn baz() -> Result<()> {
    Err(anyhow::anyhow!("baz error"))
}

fn main() {
    if let Err(e) = foo() {
        println!("{}", e);
    }
}
```

* `{:?}`の場合

エラーの文字列、スタックされたエラーの文字列が出力されます。上記の例で`{}`の代わりに`{:?}`を使うと以下が出力されます。

```rust
foo error

Caused by:
    0: bar error
    1: baz error
```
また、前述したbacktrace機能が使える状態になっており、`RUST_BACKTRACE=1`の環境変数を設定している場合は、上記のエラー情報にプラスしてbacktraceが出力されます。

```
foo error

Caused by:
    0: bar error
    1: baz error

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
      std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
      std::backtrace::Backtrace::create
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/backtrace.rs:316:13
   1: anyhow::error::<impl anyhow::Error>::msg
             at /Users/yukinari/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.45/src/error.rs:79:36
   2: anyy::baz
             at ./src/main.rs:14:9
   3: anyy::bar
             at ./src/main.rs:9:5
   4: anyy::foo
             at ./src/main.rs:4:5
   5: anyy::main
             at ./src/main.rs:18:21
   ...
```

* `{:#}`の場合

エラーの文字列、スタックされたエラーが一行で出力されます。サーバープログラム等でエラーをログに残したい場合はこれがおすすめです。

```
foo error: bar error: baz error
```

* `{:#?}`の場合

`anyhow::Error`がpretty printされます。あまり用途が思いつかないです。

```
Error {
    context: "foo error",
    source: Error {
        context: "bar error",
        source: "baz error",
    },
}
```

## `.context`を使う

anyhowには`Context`というトレイトがあり、`std::error::Error`を実装しているエラー型に新たにエラーを追加しつつ`anyhow::Error`に変換することができます。

```rust
use anyhow::{Context, Result};

fn foo() -> Result<()> {
    std::fs::open("config.yml").context("Failed to open config file")?;

    ...
}
```

## `.with_context`を使う

以下のような`format!`してエラー文を作ったりする場合だと`.context`だとエラーじゃなくても毎回`format!`が呼ばれてしまいます。`with_context`を使えばクロージャを渡せるので`format!`はエラー時のみ呼ばれるようにできます。

```rust
use anyhow::{Context, Result};

fn foo() -> Result<()> {
    let path = "config.yml";
    std::fs::open(path).context(|| format!("Failed to open config file: {}", path))?;

    ...
}
```

## Optionに対して`.context`を使う

意外に知らない人が多いですが、`anyhow::Context`はOption<T>に対して[実装されている](https://docs.rs/anyhow/latest/anyhow/trait.Context.html#impl-Context%3CT,+Infallible%3E-for-Option%3CT%3E)ので、`.context`、`.with_context`が使えます。パラメータのバリデーションするような場面ではとても便利です。

```rust
fn validate(param: Param) -> anyhow::Result<()> {
    param.foo.context("foo is missing")?;
    param.bar.context("bar is missing")?;
}
```

## `use anyhow::Context as _`で名前空間汚染を防ぐ

比較的新しい[Underscore Import](https://doc.rust-lang.org/reference/items/use-declarations.html#underscore-imports)という機能によって

```rust
use anyhow::Context as AnyhowContext;
```
のようにエイリアスを付けていたのが、`_`を使えるようになりました。

```rust
use anyhow::Context as _;
```

詳しくは[anyhow::Context を use したいが名前が被ってしまうときの解決策 -> impl-only-use](https://zenn.dev/magurotuna/articles/2c4037b75f7e51)を参照。

## `anyhow!`を使う

`anyhow!`マクロを使えば簡単に`anyhow::Error`を作れます。

1. エラー型を渡す

```rust
use anyhow::{Result, anyhow};

fn foo() -> Result<()> {
    std::fs::File::open("a.yml").map_err(|e| anyhow!(e))?;
    ...
}
```

2. 文字列を渡す

```rust
use anyhow::{Result, anyhow};

fn validate(s: &str) -> Result<()> {
    if s.len() >= 10 {
        return Err(anyhow!("Length must be less than 10"));
    }
    ...
}
```

3. `format!`スタイルを使う

```rust
use anyhow::{Result, anyhow};

fn validate(s: &str) -> Result<()> {
    if s.len() >= 10 {
        return Err(anyhow!("Length of string \"{}\" must be less than 10", s));
    }
    ...
}
```

筆者の経験上では2か3を使う場合がほとんどでした。1の場合はマクロを使う代わりに`anyhow::Error::from`や`.context`を使っていました。

## `bail!`を使う

上記の2, 3のようなケースは`bail!`を使うともっと簡単に書けます。

```rust
use anyhow::{Result, bail};

fn validate(s: &str) -> Result<()> {
    if s.len() >= 10 {
        bail!("Length of string \"{}\" must be less than 10", s);
    }
    ...
}
```

つまり`bail!`は`return Err(anyhow!(...))`の簡略化した書き方です。

## `ensure!`を使う

上記の例は`ensure!`を使うとさらに短く書けます。

```rust
use anyhow::{Result, ensure};

fn validate(s: &str) -> Result<()> {
    ensure!(s.len() < 10, "Length of string \"{}\" must be less than 10", s);
    ...
}
```

[^1]: [Rustエラーライブラリのトレンド解説（2020年1月版）](https://qiita.com/dalance/items/7e0fa481626c76d59f65)
[^2]: [Rust エラー処理2020 - 電気ひつじ牧場](https://cha-shu00.hatenablog.com/entry/2020/12/08/060000)
[^3]: [rust のエラーライブラリは failure を使わないでください](https://qiita.com/legokichi/items/d76b6aa5dac2ad781bda#エラー間の変換を書く)
